# Generated by Django 3.2.5 on 2021-12-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'admin'), (2, 'author'), (3, 'customer')], null=True),
        ),
    ]
