# Generated by Django 3.2.5 on 2021-12-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0003_alter_userinfo_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='userinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ebook.userinfo'),
        ),
        migrations.CreateModel(
            name='NovelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ebook.novel')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ebook.tag')),
            ],
        ),
    ]
