# Generated by Django 3.2.5 on 2021-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0004_auto_20211229_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='thumbnail',
            field=models.ImageField(blank=True, default='static/images/placeholder.png', null=True, upload_to='static/thumbnail'),
        ),
    ]
