# Generated by Django 3.2.5 on 2021-12-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0005_alter_novel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='thumbnail',
            field=models.FileField(blank=True, default='placeholder.png', null=True, upload_to='images/'),
        ),
    ]
