# Generated by Django 3.2.5 on 2021-12-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0007_auto_20211229_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(default='hello this is content'),
            preserve_default=False,
        ),
    ]
