# Generated by Django 3.2.5 on 2021-12-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0008_alter_chapter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novel',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images/'),
        ),
    ]
