# Generated by Django 3.2.5 on 2021-12-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0012_alter_novel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='slug',
        ),
    ]
