# Generated by Django 3.2.5 on 2021-12-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0013_remove_novel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
