# Generated by Django 3.2.5 on 2022-01-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0028_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='number_rating',
        ),
        migrations.AddField(
            model_name='novel',
            name='ee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
