# Generated by Django 3.2.5 on 2022-01-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0029_auto_20220109_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='ee',
            new_name='number_rating',
        ),
    ]
