# Generated by Django 3.2.5 on 2022-01-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0032_userinfo_lock_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ban_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lock_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
