# Generated by Django 3.2.5 on 2022-01-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0038_chapter_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
