# Generated by Django 3.2.5 on 2022-01-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0039_auto_20220120_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
