# Generated by Django 3.2.5 on 2022-01-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0040_novel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
